name: Issue a GitHub Release

on:
  push:
    tags:
      - 'v**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18.x
      - name: Bundle
        run: |
          npm install
          npm run bundle:core
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: js-single-file-bundle
          path: ./lib/enre-ts.js
  release:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download Artifact
        uses: actions/download-artifact@v4
        with:
          name: js-single-file-bundle
      - name: Resolve Git Tag
        id: tag
        uses: devops-actions/action-get-tag@v1.0.2
        with:
          strip_v: true
          default: 0.0.0
      - name: Rename Artifact
        run: |
          mv enre-ts.js enre-ts-${{ steps.tag.outputs.tag }}.js
      - name: Create a Release
        uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          prerelease: false
          files: enre-ts-${{ steps.tag.outputs.tag }}.js

